title: Yong Sook Prasit Attavit
logo: /assets/img/Github_Pages_ProfilePhoto.jpg
description: Actively looking for opportunities to transition into the field of data analytics
show_downloads: true
theme: jekyll-theme-minimal
